# See https://github.com/github/safe-settings/tree/main-enterprise/docs/sample-settings for example settings
# and https://docs.github.com/en/rest/reference/repos#update-a-repository for
# the GitHub REST API definitions

{}
